config/routes.rb
Rails.application.routes.draw do
  resources :players
  
  root 'players#index'

end

app/models/player.rb
class Player < ActiveRecord::Base

	validates :email, :name, :username, :points, presence: true
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
    validates :username, uniqueness: true, length: 5..20, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
    validates :points, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :active, exclusion: { in: [nil] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  end

  def new
  	@player = Player.new
  	
  end

  def create
  	@player = Player.new(player_params)
    
    if @player.save
      
      flash[:notice] = "El jugador se ha creado"
    end
    render 'new'
  	
  end

  private

  def player_params
  	params.require(:player).permit(:email, :name, :username, :points, :active)
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/index.html.erb
<h1>Vamos a jugar </h1>
<h3>¡Para empezar a jugar necesitas crear tu jugador!</h3>

<%= link_to 'Nuevo Jugador', new_player_path %>

app/views/players/new.html.erb
<h1>Crea un nuevo jugador</h1>

<%= form_for @player do |f| %>

<%= flash[:notice] %>

<% if @player.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@player.errors.count, "error") %> prohibited
        this player from being saved:
      </h2>
      <ul>
        <% @player.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
   <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>
 <p>
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </p>

  <p>
    <%= f.label :active %><br>
    <%= f.check_box :active, {}, "true", "false" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>